[build]
  command = "pnpm build"
  publish = "apps/nextjs/.next"
  base = "."

[build.environment]
  NODE_VERSION = "22"
  PNPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_version = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
